# Generated by Django 4.1.7 on 2023-10-25 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adTitle', models.CharField(max_length=255)),
                ('adText', models.TextField()),
                ('adFile', models.FileField(upload_to='files/')),
                ('adCategory', models.CharField(choices=[('TS', 'Танки'), ('HS', 'Хилы'), ('DD', 'ДД'), ('SR', 'Торговцы'), ('GM', 'Гилдмастер'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('TR', 'Кожевники'), ('PN', 'Зельевары'), ('SM', 'Мастера заклинаний')], default='TS', max_length=2)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyText', models.TextField()),
                ('replyCreateDate', models.DateTimeField(auto_now_add=True)),
                ('replyAd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.ad')),
                ('replyAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.author')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='adAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.author'),
        ),
    ]
