# Generated by Django 4.1.7 on 2023-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0002_alter_ad_adtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='adFile',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='adText',
            field=models.TextField(),
        ),
    ]
